#!/bin/bash
for d in `nmcli -t d |grep -e :connected |grep -e wifi -e ethernet|awk -F : '{print $1}'`;
do
	echo "Updating DNS for $d"
	nmcli d mod $d ipv4.dns "1.1.1.3 1.0.0.3"
	nmcli d mod $d ipv6.dns "2606:4700:4700::1113 2606:4700:4700::1003"
done
